### ISSUE TITLE
observe connection state

### ISSUE THREAD

**Issue by sebastian-alfers** [thenewmotion/akka-rabbitmq#13]
Hi and thanks for you great work on this! 

Is there a way see (observe) if the client is connected to rabbit or not (connection broken) from the outside?

**Comment by reinierl** [comment]
Not really. Well, you could send do something like:

```
channelActor ! ChannelMessage(_ => self() ! true, dropIfNoChannel = true)
```

and that would send "true" to the actor executing this if the channel is alive, and not do something otherwise.

However I think that allowing such observation creates exactly the problems this library aims to solve. What good is a "yes" or "no" answer when the situation may have changed already in the time between the check and the delivery of the answer?

**Comment by sebastian-alfers** [comment]
I agree on that. But how can I queue messages if the connection is dead and sending them after connection is back again?

**Comment by reinierl** [comment]
The ChannelActor does that for you automatically. Internally, it does not ask RabbitMQ if the connection is open, but just tries to execute an operation on the channel, and marks the channel as unavailable in case the operation fails.

**Comment by sebastian-alfers** [comment]
Are you sure? I was sending messages to a ChannelActor and saw them comming in.
Then I stopped rabbit, but continued to send messages.
Then I stopped sending messages and started rabbit again, but no messages came in

**Comment by reinierl** [comment]
Hmm that sounds like something is going wrong then.

Did you wait long enough for akka-rabbitmq to reconnect (10 seconds)? Did
you wait for Rabbit to index its persistent state again and fully start up?

2015-07-16 8:49 GMT+02:00 Sebastian Alfers <notifications@github.com>:

**Comment by sebastian-alfers** [comment]
sorry, I was wrong and deleted my comment. Work great

**Comment by AbacusIntegrationPlatform** [comment]
Sorry for commenting on this so late, but in my case the message is getting lost as when the Rabbit MQ server is down and during that time if my Application crashes, all my queued up messages in the Actor is getting lost. Is there a way to throw the error back rather than persisting inside the actor when the connection is broken ?
