### ISSUE TITLE
A potential Bug

### ISSUE THREAD

**Issue by wpc009** [thenewmotion/akka-rabbitmq#27]
When connection with rabbitmq server breaks. All ChannelActor drop old channel and require new channel from connectionActor.
When connection recovered. The ConnectionActor send each children a new channel. And then it receive the new channel require sent by channelactors. This will cause duplicated channel created. And force close the previous channel which will cause unexpected `ShutdownSignalException`.

**Comment by reinierl** [comment]
Thanks for the report! We had some issues like that in the past and we thought we fixed them. I'm going to look into this.

**Comment by reinierl** [comment]
Can you elaborate a bit more on how this would be a problem?

Yes, it's possible that both the ConnectionActor and the ChannelActor start recovering. However, if the ChannelActor gets a second new channel from the ConnectionActor, this will be handled correctly as far as I can see. The ShutdownSignalException for the "first" new channel will be ignored because we check if this exception is about the current channel, and it is not.

Both the set-up of the new channel, and the shutdown signal are processed as Akka messages by the ChannelActor, so every `ChannelMessage` is processed on one of the two connections and the close never happens while a user operation with the channel is in progress.

**Comment by wpc009** [comment]
When the ChannelActor  receive a new Channel, it will close the old channel which will cause problem. 
Because the old channel is in use. There exists some reading or writing I/O operation which will be interrupted by the `close` of the old Channel.

**Comment by wpc009** [comment]
I will make a Pull request for this.

**Comment by DieMyst** [comment]
I have same problem, as in this issue. How can I avoid it now?

**Comment by reinierl** [comment]
You should not let the reference to the channel escape from the closures passed to the ChannelActor with `ChannelMessage`. Then you should be fine.

**Comment by reinierl** [comment]
It also turns out that op-rabbit was letting the channel reference escape this way (see https://github.com/SpinGo/op-rabbit/issues/72). Closing this issue because it was not a malfunction of akka-rabbitmq.
